/*
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.


a^a = 0

abcd
abcde

c = a ^ b ^ c ^ d ^ a ^ b ^ c ^ d ^ e
= a ^ a ^ b ^ b ^ c ^ c ^ d ^ d ^ e
= 0 ^ 0 ^ 0 ^ 0 ^ e
= 0 ^ 0 ^ e
= 0 ^ e
= e


*/

class Solution{
    public char findTheDiff(String s, String t){
        if(s == null || t == null) throw new IllegalArgumentException();
        // 把was added 的 element取出来 做异或操作
        char c = t.charAt(t.length() - 1);
        // 因为t比s多一个，所以用t最后一个去异或
        for(int i = 0; i < s.length(); i++){
            c ^= s.charAt(i) ^ t.charAt(i);
        }
        return c;
    }
}